language: perl

sudo: false

perl:
    - "5.26"

addons:
    apt:
        packages:
            - gzip
            - bzip2
            - zip
            - unzip
            - xz
            
install:
    - "export PATH=$PWD:$PATH"

script:
    - "! any2fasta"
    - "any2fasta -v"
    - "any2fasta -h"
    - "! any2fasta -x"
    - "any2fasta /dev/null 2>&1 | grep 'ERROR'"
    - "any2fasta test.noseq.gff 2>&1 | grep 'ERROR'"
    - "any2fasta test.gbk | grep -m 3 '^>'"
    - "any2fasta test.gff | grep -m 3 '^>'"
    - "any2fasta test.fna | grep -m 3 '^>'"
    - "any2fasta test.gfa | grep -m 3 '^>'"
    - "any2fasta    test.fna | grep 'CRYANT'"
    - "any2fasta -n test.fna | grep 'CNNANT'"
    - "any2fasta test.gfa | grep '^>24292$'"
    - "any2fasta -l test.gbk | grep 'taagaatgagtagaaggttttga'"
    - "any2fasta -u test.gbk | grep 'TAAGAATGAGTAGAAGGTTTTGA'"
    - "any2fasta -f '%v' test.gbk  | grep -m 1 -F '>NZ_AHMY02000075.1'"
    - "any2fasta -f '%o' test.gbk  | grep -m 1 -F '>Leptospira'"
    - "any2fasta - < test.gbk  | grep -m 1 -F '>Leptospira'"
    - "gzip -c test.gbk | any2fasta - | grep -m 1 -F '>Leptospira'"
    - "bzip2 -c test.gbk | any2fasta - | grep -m 1 -F '>Leptospira'"
    - "zip test.gbk.zip test.gbk"
    - "any2fasta test.gbk.zip | grep -m 1 -F '>Leptospira'"
